const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),departmentPhone='918810355335';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let apps=[];
const courseSelect=$('#courseSelect');
const offerDeadline=new Date('2026-10-01T00:00:00+05:30');
function updateCourseInfo(){const ramzan=courseSelect.value.startsWith('Ramzan');$('#selectedSession').textContent=ramzan?'Ramzan · 4th Session':'2027—28';$('#courseNote').textContent=ramzan?'Started 1 Oct 2026 · online · girls only · 11 AM or 4 PM. Contact admissions to confirm late enrollment.':'Nizami course · 2027–2028 session.';if(ramzan&&Date.now()<offerDeadline.getTime())$('#feeNote').textContent='Offer today (30 Sept 2026): ₹200 admission fee · no monthly fee. ';else if(ramzan)$('#feeNote').textContent='Regular fee: ₹200 admission fee + ₹100 monthly fee. ';else $('#feeNote').textContent='Nizami course admission fee: ₹300 (non-refundable). ';}
courseSelect.addEventListener('change',updateCourseInfo);updateCourseInfo();
if(Date.now()<offerDeadline.getTime())$('#ramzanOffer').innerHTML='<b>ONE-DAY OFFER · 30 SEPT 2026</b><span>Ramzan course: pay ₹200 admission only · monthly fee waived for admissions today</span>';else $('#ramzanOffer').innerHTML='<b>SPECIAL OFFER ENDED · 30 SEPT 2026</b><span>Contact admissions to confirm current Ramzan course availability and fees.</span>';
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'The request could not be completed.');return data}
$('.menu-btn').addEventListener('click',()=> $('nav').classList.toggle('open'));$$('nav a').forEach(a=>a.addEventListener('click',()=> $('nav').classList.remove('open')));
function toDataUrl(file){return new Promise((resolve,reject)=>{if(!file)return resolve(null);const reader=new FileReader();reader.onload=()=>resolve({name:file.name,data:reader.result});reader.onerror=()=>reject(Error('Could not read selected file.'));reader.readAsDataURL(file)})}
$('#admissionForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const button=form.querySelector('[type=submit]');button.disabled=true;button.textContent='Submitting…';try{const fd=new FormData(form),data=Object.fromEntries(fd.entries());const photo=await toDataUrl(form.elements.photo.files[0]),document=await toDataUrl(form.elements.document.files[0]);delete data.photo;delete data.document;const result=await api('/api/applications',{method:'POST',body:JSON.stringify({data,files:{photo,document}})});const summary=`New admission application ${result.id}\n\nStudent: ${data.studentName}\nFather/Guardian: ${data.fatherName}\nDOB: ${data.dob}\nCourse: ${data.course}\nMobile: ${data.mobile}\nEmail: ${data.email||'Not provided'}\nAddress: ${data.address}\nPrevious school: ${data.previousSchool||'Not provided'}\nHostel: ${data.hostel}\n\nPlease contact the applicant regarding admission.`;const wa=`https://wa.me/${departmentPhone}?text=${encodeURIComponent(summary)}`;const msg=$('#successMessage');msg.hidden=false;msg.innerHTML=`<b>Application received.</b> Reference: <strong>${esc(result.id)}</strong>. To notify admissions, <a class="wa-send" href="${wa}" target="_blank" rel="noopener">open WhatsApp and tap Send ↗</a>. Our team will follow up at ${esc(data.mobile)}.`;form.reset();courseSelect.selectedIndex=0;updateCourseInfo();msg.scrollIntoView({behavior:'smooth',block:'center'})}catch(err){alert(err.message)}finally{button.disabled=false;button.innerHTML='Submit application <span>↗</span>'}});
$('#adminOpen').onclick=e=>{e.preventDefault();$('#adminModal').hidden=false;$('#loginView').hidden=false;$('#dashboardView').hidden=true;$('#adminPassword').value=''};$('#adminClose').onclick=()=>$('#adminModal').hidden=true;$('.modal-backdrop').onclick=()=>$('#adminModal').hidden=true;document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#adminModal').hidden=true});
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.currentTarget.querySelector('[type=submit]');button.disabled=true;try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('#adminPassword').value})});$('#loginView').hidden=true;$('#dashboardView').hidden=false;await renderApps()}catch(err){alert(err.message)}finally{button.disabled=false}});
async function renderApps(){try{apps=await api('/api/admin/applications')}catch(err){$('#applicationList').innerHTML=`<div class="empty">${esc(err.message)}</div>`;return}const q=$('#searchApps').value.toLowerCase(),status=$('#filterStatus').value,counts={All:apps.length,New:0,Approved:0,Rejected:0};apps.forEach(a=>counts[a.status]=(counts[a.status]||0)+1);$('#stats').innerHTML=Object.entries(counts).map(([k,v])=>`<div class="stat"><b>${v}</b><span>${k} applications</span></div>`).join('');const filtered=apps.filter(a=>(status==='All'||a.status===status)&&`${a.data.studentName} ${a.data.mobile} ${a.id}`.toLowerCase().includes(q));$('#applicationList').innerHTML=filtered.length?filtered.map(a=>`<article class="app-row"><div class="app-row-head"><div><h4>${esc(a.data.studentName)}</h4><p>${esc(a.id)} · ${esc(a.data.course)} · ${esc(a.data.mobile)}</p></div><span class="status">${esc(a.status)}</span></div><p>Guardian: ${esc(a.data.fatherName)} · DOB: ${esc(a.data.dob)} · Hostel: ${esc(a.data.hostel)} · Submitted: ${new Date(a.created).toLocaleDateString()}</p><div class="row-actions"><button onclick="viewApp('${esc(a.id)}')">View / Print</button>${a.files.photo?`<button onclick="openFile('${esc(a.id)}','photo')">Student photo</button>`:''}${a.files.document?(a.files.document.mime.startsWith('image/')?`<button class="document-thumb" onclick="openFile('${esc(a.id)}','document')"><img src="/api/admin/files/${esc(a.id)}/document" alt="Student Aadhaar or identity card photo" loading="lazy"><span>View ID card image</span></button>`:`<button onclick="openFile('${esc(a.id)}','document')">Open ID document (PDF)</button>`):''}<button class="approve" onclick="setStatus('${esc(a.id)}','Approved')">Approve</button><button class="reject" onclick="setStatus('${esc(a.id)}','Rejected')">Reject</button><button onclick="editApp('${esc(a.id)}')">Edit details</button><button onclick="deleteApp('${esc(a.id)}')">Delete</button></div></article>`).join(''):'<div class="empty">No applications found.</div>'}
window.setStatus=async(id,status)=>{try{await api(`/api/admin/applications/${id}`,{method:'PATCH',body:JSON.stringify({status})});await renderApps()}catch(e){alert(e.message)}};window.deleteApp=async id=>{if(confirm('Delete this application and its saved files?'))try{await api(`/api/admin/applications/${id}`,{method:'DELETE'});await renderApps()}catch(e){alert(e.message)}};window.editApp=async id=>{const a=apps.find(x=>x.id===id);if(!a)return;const keys=Object.keys(a.data),menu=keys.map((k,i)=>`${i+1}. ${k.replace(/[A-Z]/g,m=>' '+m.toLowerCase())}`).join('\n'),choice=prompt('Choose a detail to update by number:\n'+menu);if(choice===null)return;const key=keys[Number(choice)-1];if(!key){alert('Choose a number from the list.');return}const value=prompt('Update '+key.replace(/[A-Z]/g,m=>' '+m.toLowerCase()),a.data[key]||'');if(value===null)return;const data={...a.data,[key]:value};try{await api(`/api/admin/applications/${id}`,{method:'PATCH',body:JSON.stringify({data})});await renderApps()}catch(e){alert(e.message)}};window.openFile=id=>{};window.openFile=(id,kind)=>window.open(`/api/admin/files/${id}/${kind}`,'_blank','noopener');window.viewApp=id=>{const a=apps.find(x=>x.id===id);if(!a)return;const labels={studentName:'Student name',fatherName:'Father / guardian',motherName:'Mother',dob:'Date of birth',gender:'Gender',idNumber:'Identity document number',mobile:'Mobile',email:'Email',address:'Address',course:'Course / class',previousClass:'Previous education',previousSchool:'Previous Madrasa / school',hostel:'Hostel',occupation:'Guardian occupation',guardianMobile:'Guardian mobile',emergencyName:'Second contact name',emergencyMobile:'Second contact mobile'};const details=Object.entries(a.data).map(([k,v])=>`<p><b>${esc(labels[k]||k)}:</b> ${esc(v)}</p>`).join('');const w=window.open('','_blank');if(!w)return alert('Allow pop-ups to view and print the application.');w.document.write(`<!doctype html><meta charset="utf-8"><title>${esc(a.id)}</title><style>body{font:15px Arial;max-width:800px;margin:35px auto;color:#153c33}h1{color:#073d32}p{border-bottom:1px solid #ddd;padding:8px 0}button{padding:10px 18px}</style><h1>Jamia tul Banat — Application</h1><h2>${esc(a.id)} · ${esc(a.status)}</h2><p>Submitted ${new Date(a.created).toLocaleString()}</p>${details}<button onclick="print()">Print application</button>`)};$('#searchApps').addEventListener('input',renderApps);$('#filterStatus').addEventListener('change',renderApps);$('#exportCsv').onclick=()=>{if(!apps.length)return alert('No applications to export.');const fields=['id','status','created',...new Set(apps.flatMap(x=>Object.keys(x.data)))];const csv=[fields.map(q=>`"${q.replaceAll('"','""')}"`).join(','),...apps.map(x=>fields.map(k=>`"${String(x[k]??x.data[k]??'').replaceAll('"','""')}"`).join(','))].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='jamia-admissions.csv';a.click();URL.revokeObjectURL(a.href)};


$('#adminLogout').addEventListener('click',async()=>{try{await api('/api/admin/logout',{method:'POST',body:'{}'})}catch{}$('#dashboardView').hidden=true;$('#loginView').hidden=false;$('#adminPassword').value=''});
